### ISSUE TITLE
Unexpected error when creating benchmark database tables.

### ISSUE THREAD

**Issue by Kwon-sein** [cmu-db/benchbase#325]
Hi,
I get the following error when trying to load data for tpcc workload.
Load by this command.
```python
java -jar benchbase.jar -b tpcc -c config/mysql/sample_tpcc_config.xml --clear true --create true --load true --execute false
```

Error:
```python
Unexpected error when creating benchmark database tables.
java.sql.SQLException: Cannot add foreign key constraint
```
How can I fix this error?

**Comment by apavlo** [comment]
@Kwon-sein What version of MySQL are you using?

**Comment by Kwon-sein** [comment]
Hi,
My MySQL version is 5.7 and I using it in GCP environment.

**Comment by Kwon-sein** [comment]
Hi,
I'm sorry that I didn't explain enough in my question. I will add additional explanation.

I am using MySQL 5.7 version in GCP environment.
I ran benchmarking on the following environment.

Benchmarking on tpcc, tpch, ycsb, twitter workload with value of MySQL default setting.

The following error occureed when I load the data in **twitter**  :

![image](https://github.com/cmu-db/benchbase/assets/72485253/4573c6e1-95ff-45d1-b871-02711a74f618)

Other workloads did not produce this error.
I would like to ask why the error occurs only for 'twitter' and how to fix it.

If I have more questions, would it be possible to ask additional questions?
Thank you.

**Comment by apavlo** [comment]
@Kwon-sein Can you enable logging (`src/main/resources/log4j.properties`) for `com.oltpbenchmark.api.LoaderThread`?

What scalefactor are you using?

**Comment by Kwon-sein** [comment]
@apavlo 
Thanks for your answer.

Sure. This is logging file when I loading the data in **twitter** workload.

```python
[INFO ] 2023-06-23 17:58:28,774 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================

Benchmark:              TWITTER {com.oltpbenchmark.benchmarks.twitter.TwitterBenchmark}
Configuration:          config/mysql/myfilename.xml
Type:                   MYSQL
Driver:                 com.mysql.cj.jdbc.Driver
URL:                    jdbc:mysql://**.**.**.***:3306/benchbase?rewriteBatchedStatements=true&sslMode=DISABLED
Isolation:              TRANSACTION_SERIALIZABLE
Batch Size:             128
Scale Factor:           1.0
Terminals:              1
New Connection Per Txn: false

[INFO ] 2023-06-23 17:58:28,775 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================
[INFO ] 2023-06-23 17:58:28,786 [main]  com.oltpbenchmark.DBWorkload main - Creating new TWITTER database...
[INFO ] 2023-06-23 17:58:29,125 [main]  com.oltpbenchmark.DBWorkload main - Finished creating new TWITTER database...
[INFO ] 2023-06-23 17:58:29,291 [main]  com.oltpbenchmark.DBWorkload main - Clearing TWITTER database...
[INFO ] 2023-06-23 17:58:29,638 [main]  com.oltpbenchmark.DBWorkload main - Finished clearing TWITTER database...
[INFO ] 2023-06-23 17:58:29,638 [main]  com.oltpbenchmark.DBWorkload main - Loading data into TWITTER database...
[INFO ] 2023-06-23 17:58:29,641 [main]  com.oltpbenchmark.util.ThreadUtil runLoaderThreads - Creating a Thread Pool with a size of 16 to run 50 Loader Threads.  34 threads will be queued.
[ERROR] 2023-06-23 18:00:17,263 [Thread-6]  com.oltpbenchmark.api.LoaderThread run - Unexpected error when loading TWITTER database
[ERROR] 2023-06-23 18:00:17,263 [Thread-10]  com.oltpbenchmark.api.LoaderThread run - Unexpected error when loading TWITTER database
[ERROR] 2023-06-23 18:00:17,263 [Thread-9]  com.oltpbenchmark.api.LoaderThread run - Unexpected error when loading TWITTER database
[ERROR] 2023-06-23 18:00:17,263 [Thread-3]  com.oltpbenchmark.api.LoaderThread run - Unexpected error when loading TWITTER database
[ERROR] 2023-06-23 18:00:17,264 [Thread-10]  com.oltpbenchmark.util.ThreadUtil run - Exception in Loader Thread with message: [com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.]; will count down latch with count 45 and then exit :(
java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.oltpbenchmark.api.LoaderThread.run(LoaderThread.java:50)
	at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:145)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:86)
	at com.oltpbenchmark.api.LoaderThread.run(LoaderThread.java:44)
	... 4 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:520)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:700)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:677)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:137)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:470)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:211)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1369)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
	... 11 more
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
	at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
	at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:514)
	... 20 more
```

It is included in the above information, the scale-factor I used is 1.

**Comment by apavlo** [comment]
@Kwon-sein Are there any errors on the server-side? Are there any tuples in the tables or are they all empty?

We test Twitter on MySQL and it should be working.

**Comment by Kwon-sein** [comment]
@apavlo 
Hi,

Because benchmarking is performed after dropping and creating the benchbase database every time a test is performed, tuples do not exist in the table and benchmarking is performed in an empty state.

Even on our local server, twitter load and execute run without problems, but an error occurs only on the gcp server.

Can I get an answer on this?

**Comment by apavlo** [comment]
It's a server side error. I can't debug that from here. Try reducing BenchBase's batch size for loading.

https://github.com/cmu-db/benchbase/blob/b65943edd305f1af1c8c225eb4497a15390e4fab/config/mysql/sample_twitter_config.xml#L11

**Comment by Kwon-sein** [comment]
@apavlo 

Thank you for your reply.

I tried reducing the batch size of benchbase, but the error was not resolved.
I think it can be the problem about connecting to the gcp server.

I have an additional question. 
Does batchsize in benchbase mean the number of data input in one term? 
Then, the larger batchsize, the shorter the execution time?

**Comment by bpkroth** [comment]
> @Kwon-sein Are there any errors on the server-side? Are there any tuples in the tables or are they all empty?
> 
> We test Twitter on MySQL and it should be working.

FWIW, we test it on the `mysql:latest` docker container which is the 8.0 series now I believe.
However, after some fixups of scripts (#331), I confirmed that mysql-5 works as well:

```sh
SKIP_TESTS=true BENCHBASE_PROFILE=mysql PROFILE_VERSION=5 ./docker/build-run-benchmark-with-docker.sh tpcc
...
OK
```

**Comment by Kwon-sein** [comment]
@bpkroth 

Hi,

After this answered, I tested it in local and the gcp server.
However,as the previous error,  it runs fine in local server without errors, but errors exist within the gcp server.
Given this situation, serverside-problem seems to be correct.

Thank you for your help in resolving the issue.

If I have additional questions, leave an additional issue comment.

**Comment by Kwon-sein** [comment]
I finally solved the error!

It was confirmed that it was a flag problem along with a problem on the server.
I don't know if it can be of any help, but I'll simply write my solutions.

**MySQL: 5.7v
Benchmark in GCP server with twitter workload**

1.
Added **useSSL=false&amp;** in the server connection <url> of the xml file.

2.
In addition, appropriately assigning the value for the flag related to the _waittime_.

Thanks for your help. :)
