### ISSUE TITLE
Can't run "./mvnw clean package -P postgres" during quickstart

### ISSUE THREAD

**Issue by adkol** [cmu-db/benchbase#452]
Running the command "./mvnw clean package -P postgres" results in the following error:

![Screenshot 2024-01-19 at 2 39 33 PM](https://github.com/cmu-db/benchbase/assets/60435682/4c593919-66b0-4d72-b511-ce0ebd3c01a5)

What is causing this issue and how should I go about resolving it?

**Comment by ks-zhk** [comment]
When I was using JDK 11, I encountered the same error as you. However, the issue was resolved when I upgraded to JDK 21.So, you can try upgrading to JDK 21 to resolve this issue.
Why use JDK 21? This is because there is a corresponding configuration in the pom.xml file, as follows:
```xml
<java.version>21</java.version>
<maven.compiler.source>21</maven.compiler.source>
<maven.compiler.target>21</maven.compiler.target>
```

**Comment by adkol** [comment]
Thank you, that fixed that issue! I am still running into the following issue preventing me from building successfully and am not sure how to fix it. I have increased the heap size in my JVM and also tried setting forkCount to 0 for all of the plugins in pom.xml, but I'm still getting the same error. Any help is appreciated!
![Screenshot 2024-02-05 at 9 20 44 PM](https://github.com/cmu-db/benchbase/assets/60435682/29af529e-0c5a-49bf-8c7e-129d7917e637)

**Comment by bpkroth** [comment]
I think we'll need some more information.  Are you trying to run this with java 11?  I don't think that's supported anymore.
Have you tried to reproduce this in the devcontainer?  You should at least get a consistent java 21 environment by doing that.

**Comment by bpkroth** [comment]
Also, might be related to #457

**Comment by mdcallag** [comment]
Tried benchbase for the first time today. And also hit this error.

I am not a fan of Maven after spending a few years maintaining the Linkbench repo. So take this with a grain of salt, but why would you reformat code at compile time ([see here](https://github.com/cmu-db/benchbase/blob/8c7a9b7491f2c984c5d7f15437b0b55979a61b83/pom.xml#L373))? This is just one more thing that makes me shake my head WRT to how things are done in the land of Java+Maven+Log4j .

The reason that I ask is that people like me who try out benchbase get a lousy experience because the error from the failed formatting hides the root cause which is that we are using a too-old version of the JDK. In my case I am using the default openjdk for Ubuntu 22.04 which unfortunately only supports version 11. I then installed a more recent openjdk version (sudo apt install openjdk-21-jdk) and the build finishes without error.

**Comment by mdcallag** [comment]
I had trouble finding this bug report because the text for which I was searching was in a screen shot. Please, do the OSS world a favor and copy/paste error text so that others will find it.

**Comment by bpkroth** [comment]
> Tried benchbase for the first time today. And also hit this error.
> 
> I am not a fan of Maven after spending a few years maintaining the Linkbench repo. So take this with a grain of salt, but why would you reformat code at compile time ([see here](https://github.com/cmu-db/benchbase/blob/8c7a9b7491f2c984c5d7f15437b0b55979a61b83/pom.xml#L373))? This is just one more thing that makes me shake my head WRT to how things are done in the land of Java+Maven+Log4j .
> 
> The reason that I ask is that people like me who try out benchbase get a lousy experience because the error from the failed formatting hides the root cause which is that we are using a too-old version of the JDK. In my case I am using the default openjdk for Ubuntu 22.04 which unfortunately only supports version 11. I then installed a more recent openjdk version (sudo apt install openjdk-21-jdk) and the build finishes without error.

Don't necessarily disagree with any of this.  For my own part, I'm donating some time to help keep the lights on and add a few small features here and there, but not doing major structural changes like that.

What I did do though was create a docker image to publish a "works out of the box" image you can reference to manage some of those issues.

Unfortunately, you get other ones like needing to know a thing or two about how volume mapping works in a container environment in order to get your results in/out of the system.

**Comment by JamshedK** [comment]
For future reference, it seems like this repo is getting updated and now runs on openjdk-23. I had some issues installing openjdk-23 on Ubuntu, `sudo apt install` didn't work. Instead what I did is clone the repo with tag V2023, which I think still runs on JDK-21. Then run as usual and it runs fine. If you also have an issue with not building, most likely a jdk problem. 

<img width="692" alt="Image" src="https://github.com/user-attachments/assets/12bafc24-abf7-41c9-a80e-76ebccf37bad" />
